version: "3.9"
services:
  postgres:
    image: postgres
    container_name: app-db
    environment:
      POSTGRES_DB: "MyDB"
      POSTGRES_USER: "evgeny"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    networks:
      - net
  app:
    image: rest
    container_name: rest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      CONFIG_PATH: "local.yaml"
      LOG_PATH: "/build/logs/logs.log"
    volumes:
      - ./rest/logs:/build/logs
    networks:
      - net

networks:
  net:

