environment: "local"
storage:
  address: postgres
  port: "5432"
  user: "evgeny"
  password: "123"
  db_name: "MyDB"
  attempts_to_connect: 5
  delay_to_next_attempt: 1s
http_server:
  address: "0.0.0.0"
  port: ":8080"
  timeout: 4s
  idle_timeout: 60s
auth:
  salt: "zsdfgtjrsj153_"
  signed_key: "qbt"
  refresh_ttl: 120h
  access_ttl: 2h
  


